### PR TITLE
[WIP] Feature 64bit support

### PR DESCRIPTION
**Pull request by jwilm**
Update static libraries and tealeaf code to support iOS 64 bit builds. The bulk of the work here has been API updates for SpiderMonkey 28 (from 1.8.5).

## Cleanup
- [x] Fix any outstanding issues with native animate
- [x] Fix text display issue (it doesn't show up. sometimes.)
- [x] JSAG_MEMBER_NO_ARGS should not have args. Anything returning a value needs an alternate macro like JSAG_MEMBER_WITH_RETVAL.

### CODE REVIEW

**Comment by jwilm** [comment]
Force pushed to remove extra 23MB libjs_static.a from the history.

**Comment by rampr** [comment]
Will these changes work with devkit1 too ?

**Comment by jwilm** [comment]
It seems unlikely at this point. I would recommend upgrading to devkit2 as soon as possible. Apple doesn't require 64-bit support for titles already on the market for several months. Only new apps will require it come February.

**Comment by rampr** [comment]
I think June is the deadline for existing apps. Do you think adding these changes to devkit1 break ?

**Comment by jwilm** [comment]
The native changes **might** be ok, but there are JavaScript changes in the native-ios repository related to the build process that are definitely not going to be compatible. 

Devkit 2 presented very few API changes for applications build on devkit. Almost all of the changes were internal things related to the build process and the commands you use to build your app. If these changes are important to you, I would **highly recommend** updating devkit instead of trying to backport the changes.

**Pull request merged**
