### PR TITLE
Feature additional linker flag

### PR DESCRIPTION
**Pull request by collingreen**
- Add `additionalLinkerFlags` option to module config.
- Add warning for files added to both `code` and `arccode` lists

### CODE REVIEW

**Comment by rogueSkib** [comment]
Looks good to me!

**Comment by rampr** [comment]
So for using this functionality, the config.json could have something like the below ?

```
additionalLinkerFlags: [
 "-ObjC"
]
```

**Comment by collingreen** [comment]
@rampr - exactly. You can see it in action in the sponsorpay plugin -https://github.com/gameclosure/sponsorpay/blob/master/ios/config.json

**Comment by rampr** [comment]
Nice. What would you recommend for this case -> https://github.com/hashcube/mobihelp#note-on-ios

**Pull request merged**
